public_repo_path=imgly/starterkit-memories-editor-android
public_repo_description=Memories Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-memories
app_name=Memories Editor
package_suffix=memories
